### ISSUE TITLE
[Bug] on Item Menu

### ISSUE THREAD

**Issue by benyaminl** [ManOnDaMoon/omeka-s-module-RoleBasedNavigation#1]
Bug on Item menu/Browse menu only.
![image](https://user-images.githubusercontent.com/2817332/133471280-1893c4c3-88b6-4b03-9f96-b74bf980f120.png)

```log
Fatal error: Uncaught Error: Call to a member function id() on null in 
/var/www/repo.sib.stts.edu/application/view/common/navigation-link-form/browse.phtml:13 Stack trace: 
#0 /var/www/repo.sib.stts.edu/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include() 
#1 /var/www/repo.sib.stts.edu/vendor/laminas/laminas-view/src/Helper/Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, NULL) 
#2 [internal function]: Laminas\View\Helper\Partial->__invoke('common/navigati...', Array) 
#3 /var/www/repo.sib.stts.edu/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Laminas\View\Helper\Partial), Array) 
#4 /var/www/repo.sib.stts.edu/modules/RoleBasedNavigation/view/role-based-navigation/navigation-link-form/browse.phtml(1): Laminas\View\Renderer\PhpRenderer->__call('partial', Array) 
#5 /var/www/repo.sib.stts.edu/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/repo.s...') 
#6 /var/www/repo.sib.stts.edu/vendor/laminas/laminas-view/src/View. in /var/www/repo.sib.stts.edu/application/view/common/navigation-link-form/browse.phtml on line 13
```

**Comment by ManOnDaMoon** [comment]
Hello and thanks for reporting the bug. I'll have a look at it.

**Comment by ManOnDaMoon** [comment]
It seems the application is unable to figure out which site it is currently editing.

Could you please provide the URL you are encountering the issue on? And also provide the version info for your Omeka S install and the RoleBasedNavigation module?
One last thing to test is to disable all modules and only keep the RoleBasedNavigation to check if another issue is happening in another module.

**Comment by benyaminl** [comment]
> it should be on https://repo.sib.stts.edu/admin/site/s/r/navigation
![_20210917_172802](https://user-images.githubusercontent.com/2817332/133768390-9f202175-2279-424e-b336-3a9ff8ca98b2.JPG)

 version 1.0

**Comment by ManOnDaMoon** [comment]
Thanks. Would you be able to try the change introduced in 07c6186 ?
This should fix the site not being passed as a parameter. This is an issue related to the Omeka S v3.1.0 update with the new query builder.

**Comment by ManOnDaMoon** [comment]
I've released the fix, please reopen the issue if you still encounter the same problem.

**Comment by benyaminl** [comment]
Hello, I just check this, and Update the module. it work as it's intended. Thank you very much 🙏🙏🙏

![image](https://user-images.githubusercontent.com/2817332/134757555-5f24e3d3-c186-4315-9d96-2babf40aaa58.png)
